language: go

go:
- "1.13"

service:
- docker

jobs:
  include:
    - stage: testing Linux and Windows
      os: linux
      script: env GO111MODULE=on make clean integration-test
    - 
      os: linux
      script: env GO111MODULE=on make clean validate test
    - 
      os: windows
      script: go test ./src/
