language: go

go:
- "1.13"

service:
- docker

jobs:
  include:
    - stage: testing Linux
      os: linux
      script: env GO111MODULE=on make clean validate 
    - # stage name not required, will continue to use `test`
      os: linux
      script: env GO111MODULE=on make clean test 
    - # stage name not required, will continue to use `test`
      script: env GO111MODULE=on make clean integration-test
      os: linux
    - stage: testing Windows
      os: windows
      script: env GO111MODULE=on make clean validate 
    - # stage name not required, will continue to use `test`
      os: windows
      script: env GO111MODULE=on make clean test 

